=== JT-808/Study-informatic/XML/PR5/biblio.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="biblio">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="buch" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="buch">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="kuerzel" type="xsd:string" />
				<xsd:element name="titel" type="xsd:string" />
				<xsd:element ref="autoren" />
				<xsd:element ref="verlag" />
			</xsd:sequence>
			<xsd:attribute name="buch_id" type="xsd:ID" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="autoren">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element name="kurzInfo" type="xsd:string" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="verlag">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="link" type="xsd:string" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== JT-808/Study-informatic/XML/PR5/biblio_schema.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- XML Schema Definition aus dem XML -->
<biblio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblio.xsd">
<!-- XML Schema Definition über den Parser -->
<!-- <biblio> -->
	<buchd buch_id="_00001">
		<kuerzel>[Harold 05]</kuerzel>
		<titel>XML in a Nutshell</titel>
		<autoren>Harold, E.R.; Means, W.S.</autoren>
		<verlag>O&apos;Reilly Verlag Köln</verlag>
	</buchd>
	<buch buch_id="_00002">
		<kuerzel>[Niedermeier 05]</kuerzel>
		<titel>Java und XML</titel>
		<autoren>Niedermeier, St.; Scholz, M.
			<kurzInfo>
				<![CDATA["Stephan Niedermaier befasst sich als freier Entwickler, Trainer und Autor seit vielen Jahren mit Java und XML. Bei Galileo Computing ist zuletzt "Cocoon 2 und Tomcat" erschienen. Michael Scholz ist Anwendungs-Architekt und betreut ein J2EE-basierendes EAI-System."]]>
			</kurzInfo>
		</autoren>
		<verlag link="www.galileocomputing.de">Galileo Press Bonn</verlag>
	</buch>
</biblio>
