=== JT-808/Study-informatic/XML/PR7/beispiele/biblio/biblio.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="biblio">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="buch" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="buch">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="kuerzel" type="xsd:string" />
				<xsd:element name="titel" type="xsd:string" />
				<xsd:element name="autoren" type="xsd:string"  />
				<xsd:element name="verlag" type="xsd:string"  />
			</xsd:sequence>
			<xsd:attribute name="buch_id" type="xsd:ID" use="required" />
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== JT-808/Study-informatic/XML/PR7/beispiele/biblio/biblio.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!-- Stylesheet-Zuweisung, hat mit aelteren Browsern bzw aelteren Versionen der Browser funktioniert -->
<?xml-stylesheet type="text/xsl" href="biblio.xsl"?>

<biblio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblio.xsd">
	<buch buch_id="_00001">
		<kuerzel>[Harold 05]</kuerzel>
		<titel>XML in a Nutshell</titel>
		<autoren>Harold, E.R.; Means, W.S.</autoren>
		<verlag>O&apos;Reilly Verlag KÃ¶ln</verlag>
	</buch>
	<buch buch_id="_00002">
		<kuerzel>[Niedermeier 05]</kuerzel>
		<titel>Java und XML</titel>
		<autoren>Niedermeier, St.; Scholz, M.</autoren>
		<verlag>Galileo Press Bonn</verlag>
	</buch>
</biblio>
